import:
    - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

env:
  TERM: xterm-256color

font:
  normal:
    family: MesloLGS Nerd Font

window:
  opacity: 0.80
  decorations: Transparent
  padding:
    x: 8
    y: 30

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: On

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left, mods: Alt, chars: "\x1BB" }
